framework:
    messenger:
        default_bus: command.bus
        failure_transport: failed

        buses:
            command.bus: ~
            query.bus: ~

        transports:
            sync: 'sync://'

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_FAILURE_DSN)%'
                retry_strategy:
                    max_retries: '%messenger.default_max_retries%'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: '%messenger.default_max_retries%'

        routing:
            'Common\Domain\Message\SendEmailQueueMessage': async
            'Common\Domain\Message\SendTelegramNotificationQueueMessage': async