version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app

  php:
    build: ./
    environment:
      PHP_IDE_CONFIG: "serverName=helpdesk-ticket-api"
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: helpdesk-tickets-system-api
      MYSQL_USER: furkantopcuoglu
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"

  redis:
    image: redis:7.2
    ports:
      - "6382:6379"

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=furkantopcuoglu
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - '5672:5672'
      - '15672:15672'